jupyter:
  env:
    - name: EXTRA_PIP_PACKAGES
      value: dask_kubernetes --upgrade
  mounts:
    volumes:
      - name: my-sandbox
        hostPath:
          path: /Users/jim/Desktop/docker_sandbox/k8s-dask-sandbox/sandbox
    volumeMounts:
      - name: my-sandbox
        mountPath: /home/jovyan/sandbox
worker:
  replicas: 3
  mounts:
    volumes:
      - name: my-sandbox
        hostPath:
          path: /Users/jim/Desktop/docker_sandbox/k8s-dask-sandbox/sandbox
    volumeMounts:
      - name: my-sandbox
        mountPath: /home/jovyan/sandbox
