---
# Source: dask/templates/dask-scheduler-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dask-scheduler
  labels:
    app: dask
    heritage: "Helm"
    release: "my-dask"
    chart: dask-4.5.7
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask
      release: "my-dask"
      component: scheduler
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask
        release: "my-dask"
        component: scheduler
    spec:
      imagePullSecrets:
        null
      containers:
        - name: my-dask-scheduler
          image: "daskdev/dask:2021.1.0"
          imagePullPolicy: IfNotPresent
          args:
            - dask-scheduler
            - --port
            - "8786"
            - --bokeh-port
            - "8787"
          ports:
            - containerPort: 8786
            - containerPort: 8787
          resources:
            {}
          env:
            null
