---
# Source: dask/templates/dask-worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dask-worker
  labels:
    app: dask
    heritage: "Helm"
    release: "my-dask"
    chart: dask-4.5.7
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask
      release: "my-dask"
      component: worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask
        release: "my-dask"
        component: worker
    spec:
      imagePullSecrets:
        null
      volumes:
        - hostPath:
            path: /Users/jim/Desktop/docker_sandbox/k8s-dask-sandbox/sandbox
          name: my-sandbox
      containers:
        - name: my-dask-worker
          image: "daskdev/dask:2021.1.0"
          imagePullPolicy: IfNotPresent
          args:
            - dask-worker
            - my-dask-scheduler:8786
            - --no-dashboard
          ports:
            - containerPort: 8789
          resources:
            {}
          env:
            null
          volumeMounts:
            - mountPath: /home/jovyan/sandbox
              name: my-sandbox
